apiVersion: v1
kind: Service
metadata:
  name: daf-cacher-fe
spec:
  ports:
  - name: daf-metabase-cacher-fe
    port: 4567
    targetPort: 4567
    protocol: TCP
  selector:
    app: daf-metabase-cacher-fe
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: daf-metabase-cacher-fe-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: daf-metabase-cacher-fe
    spec:
      containers:
        - name: seeder
          image: 10.98.74.120:5000/daf-metabase-cacher:1.0
          args: ["seeder"]
          volumeMounts:
            - name: glusterfsvol
              readOnly: true
              mountPath: /etc/config.properties
              subPath: daf-cacher/config.properties
        - name: worker
          image: 10.98.74.120:5000/daf-metabase-cacher:1.0
          args: ["worker"]
          volumeMounts:
            - name: glusterfsvol
              readOnly: true
              mountPath:  /etc/config.properties
              subPath: daf-cacher/config.properties
        - name: api
          image: 10.98.74.120:5000/daf-metabase-cacher:1.0
          args: ["server"]
          volumeMounts:
            - name: glusterfsvol
              readOnly: true
              mountPath: /etc/config.properties
              subPath: daf-cacher/config.properties
          ports:
            - containerPort: 4567
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
      imagePullSecrets:
        - name: regsecret
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim

